# Generated by Django 5.0.9 on 2024-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyi', '0002_student_delete_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
