# Generated by Django 5.0.9 on 2024-11-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyi', '0010_remove_teacher_date_joined_remove_teacher_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phonenum', models.CharField(max_length=15)),
                ('mobilenum', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('guardianname', models.CharField(max_length=100)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='student_images/')),
                ('student_class', models.CharField(choices=[('JSS1', 'JSS1'), ('JSS2', 'JSS2'), ('JSS3', 'JSS3'), ('SS1', 'SS1'), ('SS2', 'SS2'), ('SS3', 'SS3')], max_length=5)),
                ('department', models.CharField(choices=[('Science', 'Science'), ('Art', 'Art'), ('Commercial', 'Commercial')], max_length=15)),
                ('adminum', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='jss1',
        ),
        migrations.DeleteModel(
            name='jss2',
        ),
        migrations.DeleteModel(
            name='jss3',
        ),
        migrations.DeleteModel(
            name='ss1',
        ),
        migrations.DeleteModel(
            name='ss2',
        ),
        migrations.DeleteModel(
            name='ss3',
        ),
    ]
