# Generated by Django 5.0.9 on 2024-11-20 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyi', '0011_student_delete_jss1_delete_jss2_delete_jss3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Science', 'Science'), ('Commercial', 'Commercial'), ('Art', 'Art')], max_length=15),
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art_student', to='anyi.student')),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_student', to='anyi.student')),
            ],
        ),
        migrations.CreateModel(
            name='JSS1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jss1_student', to='anyi.student')),
            ],
        ),
        migrations.CreateModel(
            name='JSS2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jss2_student', to='anyi.student')),
            ],
        ),
        migrations.CreateModel(
            name='JSS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jss3_student', to='anyi.student')),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='science_student', to='anyi.student')),
            ],
        ),
        migrations.CreateModel(
            name='SS1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ss1_student', to='anyi.student')),
            ],
        ),
        migrations.CreateModel(
            name='SS2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ss2_student', to='anyi.student')),
            ],
        ),
        migrations.CreateModel(
            name='SS3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ss3_student', to='anyi.student')),
            ],
        ),
    ]
