# Generated by Django 5.0.9 on 2024-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyi', '0013_remove_teacher_age_teacher_dob_teacher_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, default='+234', max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
