# Generated by Django 5.0.9 on 2024-11-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyi', '0014_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject_teacher',
            field=models.CharField(blank=True, choices=[('Mathematics', 'Mathematics'), ('English Language', 'English Language'), ('Nigerian Language', 'Nigerian Language'), ('Basic Science', 'Basic Science'), ('Social Studies', 'Social Studies'), ('Fine Arts/Creative Art', 'Fine Arts/Creative Art'), ('Agricultural Science', 'Agricultural Science'), ('Civic Education', 'Civic Education'), ('Christian Religion Studies', 'Christian Religion Studies'), ('Physical and Health Education', 'Physical and Health Education'), ('Business Studies', 'Business Studies'), ('French', 'French'), ('Computer Studies', 'Computer Studies'), ('Home Economics', 'Home Economics'), ('Basic Technology', 'Basic Technology'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Further Mathematics', 'Further Mathematics'), ('Technical Drawing', 'Technical Drawing'), ('Food and Nutrition', 'Food and Nutrition'), ('Accounting', 'Accounting'), ('Commerce', 'Commerce'), ('Book-keeping', 'Book-keeping'), ('Marketing', 'Marketing'), ('Data Processing', 'Data Processing'), ('Economics', 'Economics'), ('Government', 'Government'), ('Literature – in- English', 'Literature – in- English'), ('Christian Religion Knowledge', 'Christian Religion Knowledge'), ('Islamic Religion Knowledge', 'Islamic Religion Knowledge'), ('Geography', 'Geography')], max_length=50, null=True, verbose_name='Subject Teacher'),
        ),
    ]
