# Generated by Django 5.0.9 on 2024-12-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anyi', '0017_remove_attendance_date_remove_attendance_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='present',
            new_name='is_present',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='week',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'week', 'term')},
        ),
    ]
